# Implementation of Matrix Product

In [2]:
import numpy as np
import matplotlib.pyplot as plt


### Problem 1: Manual Calculation of Matrix Product

#### Let the first matrix be: 
$ A = \begin{bmatrix} 
	a & b & c\\
	d & e & f\\
	g & h & i
	\end{bmatrix} $
#### Let the  second matrix be: 
$ B = \begin{bmatrix} 
	r & s & t\\
	u & v & w\\
	x & y & z
	\end{bmatrix} $
#### The product of A and B will be: 
$ A x B = \begin{bmatrix} 
	ar + bu + cx & as + bv + cy & at + bw + cz\\
	dr + eu + fx & ds + ev + fy & dt + ew + fz\\
	gr + hu + ix & gs + hv + iy & gt + hw + iz
	\end{bmatrix} $

#### ==> : 
$ A x B = \begin{bmatrix} 
	(-1\cdot0)+(2\cdot0)+(3\cdot2) & (-1\cdot2)+(2\cdot2)+(3\cdot9) & (-1\cdot1)+(2\cdot-8)+(3\cdot-1)\\
	(4\cdot0)+(-5\cdot0)+(6\cdot2) & (4\cdot2)+(-5\cdot2)+(6\cdot9) & (4\cdot1)+(-5\cdot-8)+(6\cdot-1)\\
	(7\cdot0)+(8\cdot0)+(9\cdot2) & (7\cdot2)+(8\cdot2)+(9\cdot9) & (7\cdot1)+(8\cdot-8)+(9\cdot-1)
	\end{bmatrix} $

#### ==> : 
$ A x B = \begin{bmatrix} 
	6 & 29 & -20\\
	12 & 52 & 38\\
	18 & 111 & -66
	\end{bmatrix} $

### Problem 2: Calculate Numpy by Function

In [21]:
A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, 9]])
B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

product1 = np.matmul(A, B)
product2 = np.dot(A, B)
product3 = A @ B

#product1
#product2
product3

array([[  6,  29, -20],
       [ 12,  52,  38],
       [ 18, 111, -66]])

### Problem 3: Implementation of Calculation of a Certain Element

In [45]:
i = 0
j = 0
element =  np.sum(A[i, :]* B[:, j])
element

6

### Problem 4: Creating a Function that solves Matrix Multiplication

In [47]:
def calculate_Product(matrixA, matrixB):
    ### Matrix can only be multiplied if the number of rows in matrix A is equal to the number of columns in matrix B. so get the number and stor in a new variable
    rows = matrixA.shape[0]
    col = matrixB.shape[1]
    
    #create a list to store elements in array
    list = []
    if rows==col:
        for i in range(rows):
            for j in range(col):
                element = np.sum(matrixA[i, :] * matrixB[:, j].T)
                list.append(element)

        product = np.array(list).reshape(rows, col)
        return product
    else: 
        print("Product cannot be calculated as rows in matrix 1 is not equal to columns in matrix 2.")

calculate_Product(matrixA=A, matrixB=B)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [ 18, 111, -66]])

### Problem 5: Judge the Input whose Output is not Defined

In [48]:
D = np.array([[-1, 2, 3], [4, 5, 6]])
E = np.array([[-9, 8, 7], [6, -5, 4]])

calculate_Product(D, E)

Product cannot be calculated as rows in matrix 1 is not equal to columns in matrix 2.


### Problem 6: Transposition

In [51]:
A_transpose = A.T
A_transpose

calculate_Product(A_transpose, B)

array([[ 14,  69, -40],
       [ 16,  66,  34],
       [ 18,  99, -54]])